___

<a href='https://mp.weixin.qq.com/mp/appmsgalbum?__biz=Mzg2OTU4NzI3NQ==&action=getalbum&album_id=1764511202329624577&scene=126#wechat_redirect'> <img src=../../../../pic/project_logo.jpg></a>
___

# NumPy 


- https://mp.weixin.qq.com/s/lFCojLwoMmDqSnzJSBpJQg 【Numpy上】
- https://mp.weixin.qq.com/s/YzhjLGXJNaqrAfP-6QwXRw 【Numpy下】

Numpy （Numerical Python）是 Python 专门处理高维数组 (high dimensional array) 的计算的包。

<a href='https://mp.weixin.qq.com/s/lFCojLwoMmDqSnzJSBpJQg'> <img src=../../../../pic/numpy.png></a>


Numpy 运行速度快，主要用于数组计算，包含：

- N维数组 ndarray
- 广播功能 Broadcast
- 代数、变化、随机数等


官网：www.numpy.org

## 引入 NumPy

In [1]:
import numpy as np

# Numpy 数组

NumPy 数组是我们在整个课程中使用 Numpy 的主要方式。 Numpy 数组本质上有两种形式：向量和矩阵。

- 向量是严格的一维数组
- 矩阵是二维的（但注意，矩阵仍然只能有一行或一列）。

现在介绍如何创建 NumPy 数组。

## 创建 Arrays

### From a Python List

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.array(my_matrix)[:,1]

array([2, 5, 8])

In [7]:
list(zip(*my_matrix))[0]

(1, 4, 7)

## Built-in 方法

### arange

在给定的间隔内返回均匀间隔的值。

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros & ones

生成零或一的数组。

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

产生随机数组

### rand

创建给定形状的数组并填充它
来自均匀分布的随机样本。

In [17]:
np.random.seed(2)
np.random.rand(2)

array([0.4359949 , 0.02592623])

In [18]:
np.random.rand(5,5)

array([[0.54966248, 0.43532239, 0.4203678 , 0.33033482, 0.20464863],
       [0.61927097, 0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515, 0.85397529],
       [0.49423684, 0.84656149, 0.07964548, 0.50524609, 0.0652865 ],
       [0.42812233, 0.09653092, 0.12715997, 0.59674531, 0.226012  ]])

### randn

从“标准正态”分布中返回一个（或多个）样本。与均匀分布的`rand`不同

In [19]:
np.random.randn(2)

array([-0.21943638, -0.30837444])

In [20]:
np.random.randn(5,5)

array([[-4.55714773e-01, -2.12452767e+00,  5.49798242e-01,
        -1.16790025e+00,  1.08006357e+00],
       [-3.49181430e+00,  1.27004848e+00, -4.89214894e-01,
        -1.17598956e+00,  2.78601388e-01],
       [ 9.99385255e-01,  2.14521176e-05,  8.06308075e-01,
        -1.90200089e+00, -1.68871762e+00],
       [-1.93437335e+00,  1.95149052e-01,  1.51584091e+00,
         5.89388516e-02,  6.04934602e-01],
       [-2.20225580e-01, -6.88575805e-01, -2.91892165e-01,
         1.09267069e+00,  1.40473201e+00]])

### randint

返回从“低”（包括）到“高”（不包括）的随机整数。

In [21]:
np.random.randint(1,100)

92

In [22]:
np.random.randint(1,100,10)

array([97, 17, 56, 22, 44, 94, 81, 41, 71, 75])

## 数组性质（attribute）和方法（method）


In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([37, 17, 15, 30, 13, 26, 39, 43, 47, 20])

## 重塑（reshape）

返回包含具有新形状的相同数据的数组。

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max / min / argmax / argmin

这些是查找最大值或最小值的方法。或者使用 `argmin` 或 `argmax` 找到它们的索引位置。

In [27]:
ranarr

array([37, 17, 15, 30, 13, 26, 39, 43, 47, 20])

In [28]:
ranarr.max()

47

In [29]:
ranarr.argmax()

8

In [30]:
ranarr.min()

13

In [31]:
ranarr.argmin()

4

## 形状（shape）


形状是数组具有的属性（不是方法）

In [32]:
# Vector
arr.shape

(25,)

In [33]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
arr.reshape(1,25).shape

(1, 25)

In [35]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [36]:
arr.reshape(25,1).shape

(25, 1)

### 数据类型（dtype）

还可以获取数组中对象的数据类型

In [37]:
arr.dtype

dtype('int32')

# Great Job!